// Builds public/map-data.js: SVG paths of the 26 cantons and the large lakes.
// Geodata: Bundesamt für Statistik (BFS), GEOSTAT, via the swiss-maps package (non-commercial use with attribution).
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";
import { geoMercator, geoPath } from "d3-geo";

const topo = JSON.parse(readFileSync(createRequire(import.meta.url).resolve("swiss-maps/2026/ch-combined.json")));
const simple = simplify(presimplify(topo), 1e-4);

// BFS canton numbers 1..26. Half cantons have half a vote (Standesstimme) in the majority of the cantons.
const ABBR = ["ZH", "BE", "LU", "UR", "SZ", "OW", "NW", "GL", "ZG", "FR", "SO", "BS", "BL", "SH", "AR", "AI", "SG", "GR", "AG", "TG", "TI", "VD", "VS", "NE", "GE", "JU"];
const HALF = new Set(["OW", "NW", "BS", "BL", "AR", "AI"]);

const W = 1000;
const country = feature(simple, simple.objects.country);
const projection = geoMercator().fitWidth(W, country);
const path = geoPath(projection).digits(0); // whole pixels are enough at 1000 px width
const [[, y0], [, y1]] = path.bounds(country);
const H = Math.ceil(y1 - y0);
projection.translate([projection.translate()[0], projection.translate()[1] - y0]);

const cantons = feature(simple, simple.objects.cantons).features
  .map((f) => {
    const abbr = ABBR[f.id - 1];
    const [cx, cy] = path.centroid(f).map((n) => Math.round(n));
    return { id: f.id, abbr, half: HALF.has(abbr), d: path(f), cx, cy };
  })
  .sort((a, b) => a.id - b.id);
// Only lakes large enough to see on the map.
const lakes = feature(simple, simple.objects.lakes).features.filter((f) => path.area(f) > 120).map((f) => path(f));

const out = `// Generated by scripts/build-map.mjs. Geodata: Bundesamt für Statistik (BFS), GEOSTAT.
export const MAP = ${JSON.stringify({ width: W, height: H, cantons, lakes })};
`;
writeFileSync(new URL("../public/map-data.js", import.meta.url), out);
console.log(`map-data.js: ${W}x${H}, ${cantons.length} cantons, ${lakes.length} lakes, ${(out.length / 1024).toFixed(1)} KB`);
